# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import faq_pb2 as faq__pb2


class FaqGatewayStub(object):
  """ルーティング
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.FaqCreate = channel.unary_unary(
        '/faq.FaqGateway/FaqCreate',
        request_serializer=faq__pb2.FaqCreateRequest.SerializeToString,
        response_deserializer=faq__pb2.FaqCreateResponse.FromString,
        )
    self.FaqShow = channel.unary_unary(
        '/faq.FaqGateway/FaqShow',
        request_serializer=faq__pb2.FaqShowRequest.SerializeToString,
        response_deserializer=faq__pb2.FaqShowResponse.FromString,
        )
    self.FaqUpdate = channel.unary_unary(
        '/faq.FaqGateway/FaqUpdate',
        request_serializer=faq__pb2.FaqUpdateRequest.SerializeToString,
        response_deserializer=faq__pb2.FaqUpdateResponse.FromString,
        )


class FaqGatewayServicer(object):
  """ルーティング
  """

  def FaqCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FaqShow(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FaqUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FaqGatewayServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'FaqCreate': grpc.unary_unary_rpc_method_handler(
          servicer.FaqCreate,
          request_deserializer=faq__pb2.FaqCreateRequest.FromString,
          response_serializer=faq__pb2.FaqCreateResponse.SerializeToString,
      ),
      'FaqShow': grpc.unary_unary_rpc_method_handler(
          servicer.FaqShow,
          request_deserializer=faq__pb2.FaqShowRequest.FromString,
          response_serializer=faq__pb2.FaqShowResponse.SerializeToString,
      ),
      'FaqUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.FaqUpdate,
          request_deserializer=faq__pb2.FaqUpdateRequest.FromString,
          response_serializer=faq__pb2.FaqUpdateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'faq.FaqGateway', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
